name: Push

on: push

env:
  PROJECT_NAME: batproxy
  BASE_PACKAGE_NAME: github.com/batx-dev/batproxy


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          dest: build
          prefix: ${{ env.PROJECT_NAME }}
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -X ${{ env.BASE_PACKAGE_NAME }}.Version=${{ github.GITHUB_REF_NAME }}
          buildmode: default
          trimpath: true
